//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accent.ConsoleApplication.SmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.coviet.vn/SendSmsMsgWebService", ConfigurationName="SmsService.SendSmsMsgServiceSoap")]
    public interface SendSmsMsgServiceSoap {
        
        // CODEGEN: Generating message contract since element name strFunctionName from namespace http://www.coviet.vn/SendSmsMsgWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.coviet.vn/SendSmsMsgWebService/ExecuteFunc", ReplyAction="*")]
        Accent.ConsoleApplication.SmsService.ExecuteFuncResponse ExecuteFunc(Accent.ConsoleApplication.SmsService.ExecuteFuncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.coviet.vn/SendSmsMsgWebService/ExecuteFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<Accent.ConsoleApplication.SmsService.ExecuteFuncResponse> ExecuteFuncAsync(Accent.ConsoleApplication.SmsService.ExecuteFuncRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteFuncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteFunc", Namespace="http://www.coviet.vn/SendSmsMsgWebService", Order=0)]
        public Accent.ConsoleApplication.SmsService.ExecuteFuncRequestBody Body;
        
        public ExecuteFuncRequest() {
        }
        
        public ExecuteFuncRequest(Accent.ConsoleApplication.SmsService.ExecuteFuncRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.coviet.vn/SendSmsMsgWebService")]
    public partial class ExecuteFuncRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFunctionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strXmlParam;
        
        public ExecuteFuncRequestBody() {
        }
        
        public ExecuteFuncRequestBody(string strFunctionName, string strXmlParam) {
            this.strFunctionName = strFunctionName;
            this.strXmlParam = strXmlParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteFuncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteFuncResponse", Namespace="http://www.coviet.vn/SendSmsMsgWebService", Order=0)]
        public Accent.ConsoleApplication.SmsService.ExecuteFuncResponseBody Body;
        
        public ExecuteFuncResponse() {
        }
        
        public ExecuteFuncResponse(Accent.ConsoleApplication.SmsService.ExecuteFuncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.coviet.vn/SendSmsMsgWebService")]
    public partial class ExecuteFuncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteFuncResult;
        
        public ExecuteFuncResponseBody() {
        }
        
        public ExecuteFuncResponseBody(string ExecuteFuncResult) {
            this.ExecuteFuncResult = ExecuteFuncResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSmsMsgServiceSoapChannel : Accent.ConsoleApplication.SmsService.SendSmsMsgServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSmsMsgServiceSoapClient : System.ServiceModel.ClientBase<Accent.ConsoleApplication.SmsService.SendSmsMsgServiceSoap>, Accent.ConsoleApplication.SmsService.SendSmsMsgServiceSoap {
        
        public SendSmsMsgServiceSoapClient() {
        }
        
        public SendSmsMsgServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSmsMsgServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsMsgServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsMsgServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Accent.ConsoleApplication.SmsService.ExecuteFuncResponse Accent.ConsoleApplication.SmsService.SendSmsMsgServiceSoap.ExecuteFunc(Accent.ConsoleApplication.SmsService.ExecuteFuncRequest request) {
            return base.Channel.ExecuteFunc(request);
        }
        
        public string ExecuteFunc(string strFunctionName, string strXmlParam) {
            Accent.ConsoleApplication.SmsService.ExecuteFuncRequest inValue = new Accent.ConsoleApplication.SmsService.ExecuteFuncRequest();
            inValue.Body = new Accent.ConsoleApplication.SmsService.ExecuteFuncRequestBody();
            inValue.Body.strFunctionName = strFunctionName;
            inValue.Body.strXmlParam = strXmlParam;
            Accent.ConsoleApplication.SmsService.ExecuteFuncResponse retVal = ((Accent.ConsoleApplication.SmsService.SendSmsMsgServiceSoap)(this)).ExecuteFunc(inValue);
            return retVal.Body.ExecuteFuncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Accent.ConsoleApplication.SmsService.ExecuteFuncResponse> Accent.ConsoleApplication.SmsService.SendSmsMsgServiceSoap.ExecuteFuncAsync(Accent.ConsoleApplication.SmsService.ExecuteFuncRequest request) {
            return base.Channel.ExecuteFuncAsync(request);
        }
        
        public System.Threading.Tasks.Task<Accent.ConsoleApplication.SmsService.ExecuteFuncResponse> ExecuteFuncAsync(string strFunctionName, string strXmlParam) {
            Accent.ConsoleApplication.SmsService.ExecuteFuncRequest inValue = new Accent.ConsoleApplication.SmsService.ExecuteFuncRequest();
            inValue.Body = new Accent.ConsoleApplication.SmsService.ExecuteFuncRequestBody();
            inValue.Body.strFunctionName = strFunctionName;
            inValue.Body.strXmlParam = strXmlParam;
            return ((Accent.ConsoleApplication.SmsService.SendSmsMsgServiceSoap)(this)).ExecuteFuncAsync(inValue);
        }
    }
}
