//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotProject.Common.SendSmsMsgService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.coviet.vn/SendSmsMsgWebService", ConfigurationName="SendSmsMsgService.SendSmsMsgServiceSoap")]
    public interface SendSmsMsgServiceSoap {
        
        // CODEGEN: Generating message contract since element name strFunctionName from namespace http://www.coviet.vn/SendSmsMsgWebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.coviet.vn/SendSmsMsgWebService/ExecuteFunc", ReplyAction="*")]
        BotProject.Common.SendSmsMsgService.ExecuteFuncResponse ExecuteFunc(BotProject.Common.SendSmsMsgService.ExecuteFuncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.coviet.vn/SendSmsMsgWebService/ExecuteFunc", ReplyAction="*")]
        System.Threading.Tasks.Task<BotProject.Common.SendSmsMsgService.ExecuteFuncResponse> ExecuteFuncAsync(BotProject.Common.SendSmsMsgService.ExecuteFuncRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteFuncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteFunc", Namespace="http://www.coviet.vn/SendSmsMsgWebService", Order=0)]
        public BotProject.Common.SendSmsMsgService.ExecuteFuncRequestBody Body;
        
        public ExecuteFuncRequest() {
        }
        
        public ExecuteFuncRequest(BotProject.Common.SendSmsMsgService.ExecuteFuncRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.coviet.vn/SendSmsMsgWebService")]
    public partial class ExecuteFuncRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFunctionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strXmlParam;
        
        public ExecuteFuncRequestBody() {
        }
        
        public ExecuteFuncRequestBody(string strFunctionName, string strXmlParam) {
            this.strFunctionName = strFunctionName;
            this.strXmlParam = strXmlParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteFuncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteFuncResponse", Namespace="http://www.coviet.vn/SendSmsMsgWebService", Order=0)]
        public BotProject.Common.SendSmsMsgService.ExecuteFuncResponseBody Body;
        
        public ExecuteFuncResponse() {
        }
        
        public ExecuteFuncResponse(BotProject.Common.SendSmsMsgService.ExecuteFuncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.coviet.vn/SendSmsMsgWebService")]
    public partial class ExecuteFuncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteFuncResult;
        
        public ExecuteFuncResponseBody() {
        }
        
        public ExecuteFuncResponseBody(string ExecuteFuncResult) {
            this.ExecuteFuncResult = ExecuteFuncResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSmsMsgServiceSoapChannel : BotProject.Common.SendSmsMsgService.SendSmsMsgServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSmsMsgServiceSoapClient : System.ServiceModel.ClientBase<BotProject.Common.SendSmsMsgService.SendSmsMsgServiceSoap>, BotProject.Common.SendSmsMsgService.SendSmsMsgServiceSoap {
        
        public SendSmsMsgServiceSoapClient() {
        }
        
        public SendSmsMsgServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSmsMsgServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsMsgServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsMsgServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BotProject.Common.SendSmsMsgService.ExecuteFuncResponse BotProject.Common.SendSmsMsgService.SendSmsMsgServiceSoap.ExecuteFunc(BotProject.Common.SendSmsMsgService.ExecuteFuncRequest request) {
            return base.Channel.ExecuteFunc(request);
        }
        
        public string ExecuteFunc(string strFunctionName, string strXmlParam) {
            BotProject.Common.SendSmsMsgService.ExecuteFuncRequest inValue = new BotProject.Common.SendSmsMsgService.ExecuteFuncRequest();
            inValue.Body = new BotProject.Common.SendSmsMsgService.ExecuteFuncRequestBody();
            inValue.Body.strFunctionName = strFunctionName;
            inValue.Body.strXmlParam = strXmlParam;
            BotProject.Common.SendSmsMsgService.ExecuteFuncResponse retVal = ((BotProject.Common.SendSmsMsgService.SendSmsMsgServiceSoap)(this)).ExecuteFunc(inValue);
            return retVal.Body.ExecuteFuncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BotProject.Common.SendSmsMsgService.ExecuteFuncResponse> BotProject.Common.SendSmsMsgService.SendSmsMsgServiceSoap.ExecuteFuncAsync(BotProject.Common.SendSmsMsgService.ExecuteFuncRequest request) {
            return base.Channel.ExecuteFuncAsync(request);
        }
        
        public System.Threading.Tasks.Task<BotProject.Common.SendSmsMsgService.ExecuteFuncResponse> ExecuteFuncAsync(string strFunctionName, string strXmlParam) {
            BotProject.Common.SendSmsMsgService.ExecuteFuncRequest inValue = new BotProject.Common.SendSmsMsgService.ExecuteFuncRequest();
            inValue.Body = new BotProject.Common.SendSmsMsgService.ExecuteFuncRequestBody();
            inValue.Body.strFunctionName = strFunctionName;
            inValue.Body.strXmlParam = strXmlParam;
            return ((BotProject.Common.SendSmsMsgService.SendSmsMsgServiceSoap)(this)).ExecuteFuncAsync(inValue);
        }
    }
}
