// <auto-generated />
namespace BotProject.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update9076 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update9076));
        
        string IMigrationMetadata.Id
        {
            get { return "201906250305015_Update9076"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
