// <auto-generated />
namespace BotProject.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class U121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(U121));
        
        string IMigrationMetadata.Id
        {
            get { return "201903231102313_U121"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
